name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-20.04
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: salman-farooq-sh/metrics@master
        with:
          token: ${{ secrets.METRICS_EMBED_GITHUB_TOKEN }}
